name: Deploy dev to github pages

on:
  push:
    branches: [ development ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
env:
  URL: mstigter0.github.io/PagesPoC-dev/
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://${{ env.URL }}
    steps:
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
          
      - name: Checkout Dev Target
        uses: actions/checkout@v2
        with:
          repository: mstigter0/PagesPoC-dev
          path: 'deploy'
          token: ${{ secrets.PAT }}
          
      - name: Push files to target
        run: |
          cp -r build/dist/* deploy
          cd deploy
          touch .nojekyll
          echo ${{ env.URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push
          
          
